// Injects search-engine and social metadata into every public page, and
// generates sitemap.xml + robots.txt. Idempotent: re-running replaces the
// block between the SEO markers, so pages never accumulate duplicate tags.
// Run with `npm run build:seo`. The internal sales portal is left untouched.
import { readFile, writeFile, readdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';

const root = fileURLToPath(new URL('../', import.meta.url));
const SITE = 'https://creaiva.online';
const START = '<!-- SEO:START (generated by scripts/build-seo.mjs) -->';
const END = '<!-- SEO:END -->';

// Public pages, mirroring scripts/build-knowledge.mjs. The internal
// sales-pricing.html already carries noindex and is deliberately excluded.
const rootPages = ['index.html', 'contact.html', 'our-team.html', 'portfolio.html', 'portfolio-photography.html', 'ecommerce-white-label.html'];
const paths = [...rootPages];
for (const folder of ['services', 'solutions']) {
  for (const name of (await readdir(resolve(root, folder))).sort()) {
    if (name.endsWith('.html')) paths.push(`${folder}/${name}`);
  }
}

// Per-page social share image. Falls back to the wordmark when a page has
// no dedicated artwork, so every card is branded and valid.
const LOGO = `${SITE}/creaiva-logo-horizontal.png`;
const ogImages = {
  'index.html': LOGO,
  'contact.html': LOGO,
  'our-team.html': LOGO,
  'portfolio.html': LOGO,
  'portfolio-photography.html': `${SITE}/assets/portfolio/product-premium-scent.webp`,
  'ecommerce-white-label.html': `${SITE}/assets/ecommerce-white-label/fashion.webp`,
  'services/logo-branding.html': `${SITE}/assets/thumbnails/service-branding.jpg`,
  'services/2d-animation.html': `${SITE}/assets/thumbnails/service-2d.jpg`,
  'services/3d-animation.html': `${SITE}/assets/thumbnails/service-3d.jpg`,
  'services/motion-design.html': `${SITE}/assets/thumbnails/service-motion.jpg`,
  'services/ai-video-realistic.html': `${SITE}/assets/thumbnails/service-ai-media.jpg`,
  'services/photography-videography.html': `${SITE}/assets/thumbnails/service-photography.jpg`,
  'services/website-design.html': `${SITE}/assets/thumbnails/service-web.jpg`,
  'services/platform-web.html': `${SITE}/assets/thumbnails/service-crm.jpg`,
  'services/social-media-management.html': `${SITE}/assets/thumbnails/service-social.jpg`,
  'solutions/ai-content-studio.html': `${SITE}/assets/thumbnails/solution-ai-content.jpg`,
  'solutions/brand-launch-package.html': `${SITE}/assets/thumbnails/solution-brand-launch.jpg`,
  'solutions/corporate-presentations.html': `${SITE}/assets/thumbnails/solution-presentations.jpg`,
  'solutions/digital-marketing-suite.html': `${SITE}/assets/thumbnails/solution-marketing.jpg`,
  'solutions/ecommerce-web-platforms.html': `${SITE}/assets/thumbnails/solution-ecommerce.jpg`,
  'solutions/growth-analytics.html': `${SITE}/assets/thumbnails/solution-growth.jpg`,
  'solutions/interactive-experience.html': `${SITE}/assets/thumbnails/solution-interactive.jpg`,
};

// Focused keyword sets per page. Kept honest to what each page actually
// offers; the Dubai / UAE modifiers carry the local-search intent.
const GEO = 'Dubai, UAE';
const keywords = {
  'index.html': 'AI creative agency Dubai, AI video production Dubai, AI content creation Dubai, creative agency Dubai, digital creative agency Dubai, AI marketing agency UAE, digital advertising agency Dubai, generative AI studio Dubai',
  'contact.html': 'contact CREAIVA Dubai, contact creative agency Dubai, hire AI studio Dubai, digital advertising quote UAE',
  'our-team.html': 'creative team Dubai, AI design studio team, digital agency experts UAE',
  'portfolio.html': 'AI creative agency portfolio Dubai, creative agency portfolio Dubai, branding case studies, AI campaign work UAE',
  'portfolio-photography.html': 'professional photographer Dubai, product photography Dubai, food photography UAE, wedding photography Dubai, family photography',
  'ecommerce-white-label.html': 'white label ecommerce design Dubai, custom ecommerce storefront UAE, ecommerce UI design, online store design Dubai, mobile commerce design',
  'services/logo-branding.html': 'branding agency Dubai, logo design Dubai, brand identity design, visual identity Dubai',
  'services/2d-animation.html': '2D animation studio Dubai, explainer video production, character animation UAE',
  'services/3d-animation.html': '3D animation company Dubai, product visualization, 3D rendering UAE, CGI studio',
  'services/motion-design.html': 'motion graphics company Dubai, motion design Dubai, kinetic typography UAE',
  'services/ai-video-realistic.html': 'AI video production Dubai, generative video, AI commercial UAE, realistic AI footage',
  'services/photography-videography.html': 'photography and videography Dubai, product videography, campaign photography UAE',
  'services/website-design.html': 'web design company Dubai, website design Dubai, landing page design, SEO web design',
  'services/ecommerce.html': 'ecommerce website development Dubai, online store development, Shopify agency UAE',
  'services/platform-web.html': 'web platform development Dubai, custom CRM development Dubai, dashboard development UAE',
  'services/seo-analytics.html': 'SEO agency Dubai, technical SEO UAE, analytics setup, search optimization',
  'services/social-media-management.html': 'social media management Dubai, social media agency UAE, content marketing',
  'services/interactive-presentation.html': 'interactive presentation design Dubai, click-through demo, showroom presentation Dubai',
  'services/interactive-screen.html': 'interactive screen solutions Dubai, touchscreen kiosk, digital signage UAE',
  'services/presentation-pro.html': 'presentation design company Dubai, pitch deck design Dubai, investor presentation UAE',
  'services/lifestyle-consultancy.html': 'lifestyle consultant Dubai, life coaching UAE, wellness coaching, healthy routine coaching',
  'solutions/ai-content-studio.html': 'AI content production Dubai, AI content studio, scalable brand content UAE',
  'solutions/brand-launch-package.html': 'brand launch package Dubai, startup branding UAE, brand launch content',
  'solutions/corporate-presentations.html': 'corporate presentation design Dubai, boardroom deck, presentation system UAE',
  'solutions/digital-marketing-suite.html': 'digital marketing agency Dubai, paid ads and SEO UAE, integrated marketing',
  'solutions/ecommerce-web-platforms.html': 'ecommerce platform Dubai, connected storefront and CRM, web platform UAE',
  'solutions/growth-analytics.html': 'growth marketing Dubai, conversion optimization UAE, marketing analytics',
  'solutions/interactive-experience.html': 'interactive experience design Dubai, event technology, showroom experience UAE',
};

const esc = s => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const canonicalFor = path => (path === 'index.html' ? `${SITE}/` : `${SITE}/${path}`);
const displayName = title => title.split(' — ')[0].split(' · ')[0].trim();

// Shared organization node, referenced by @id from every page's graph so
// search engines resolve one canonical business entity across the site.
const orgNode = () => ({
  '@type': ['Organization', 'ProfessionalService'],
  '@id': `${SITE}/#organization`,
  name: 'CREAIVA',
  alternateName: 'CREAIVA Studio',
  url: `${SITE}/`,
  logo: { '@type': 'ImageObject', url: LOGO, width: 2430, height: 409 },
  image: LOGO,
  description: 'Dubai-based AI specialist and digital advertising studio crafting AI video, motion design, branding, web, and growth platforms for brands worldwide.',
  email: 'creaiva.ultra@gmail.com',
  telephone: '+971566644147',
  slogan: 'Bold Brands, Powered by Intelligence',
  address: { '@type': 'PostalAddress', addressLocality: 'Dubai', addressRegion: 'Dubai', addressCountry: 'AE' },
  areaServed: [{ '@type': 'Country', name: 'United Arab Emirates' }, { '@type': 'Place', name: 'Worldwide' }],
  knowsLanguage: ['English', 'Arabic'],
  contactPoint: {
    '@type': 'ContactPoint',
    telephone: '+971566644147',
    email: 'creaiva.ultra@gmail.com',
    contactType: 'customer service',
    availableLanguage: ['English', 'Arabic'],
    areaServed: 'AE',
  },
});

const crumb = items => ({
  '@type': 'BreadcrumbList',
  itemListElement: items.map((it, i) => ({
    '@type': 'ListItem', position: i + 1, name: it.name, item: it.url,
  })),
});

function graphFor(path, title, description, ogImage) {
  const url = canonicalFor(path);
  const name = displayName(title);

  if (path === 'index.html') {
    const org = orgNode();
    // Advertise the full service catalogue so engines map offerings to the brand.
    org.hasOfferCatalog = {
      '@type': 'OfferCatalog',
      name: 'CREAIVA Services',
      itemListElement: paths.filter(p => p.startsWith('services/')).map(p => ({
        '@type': 'Offer',
        itemOffered: { '@type': 'Service', name: displayName(titles[p]), url: canonicalFor(p) },
      })),
    };
    return [org, {
      '@type': 'WebSite', '@id': `${SITE}/#website`, url: `${SITE}/`, name: 'CREAIVA',
      description, publisher: { '@id': `${SITE}/#organization` }, inLanguage: 'en',
    }, {
      '@type': 'WebPage', '@id': `${url}#webpage`, url, name: title, description,
      isPartOf: { '@id': `${SITE}/#website` }, about: { '@id': `${SITE}/#organization` }, inLanguage: 'en',
    }];
  }

  if (path.startsWith('services/') || path.startsWith('solutions/')) {
    const isSolution = path.startsWith('solutions/');
    const hub = isSolution
      ? { name: 'Solutions', url: `${SITE}/#solutions` }
      : { name: 'Services', url: `${SITE}/#services` };
    return [{
      '@type': 'Service', '@id': `${url}#service`, name, serviceType: name, description, url,
      provider: { '@id': `${SITE}/#organization` }, image: ogImage,
      areaServed: [{ '@type': 'Country', name: 'United Arab Emirates' }, { '@type': 'Place', name: 'Worldwide' }],
    }, crumb([{ name: 'Home', url: `${SITE}/` }, hub, { name, url }]),
      { '@type': 'WebPage', '@id': `${url}#webpage`, url, name: title, description, inLanguage: 'en', primaryImageOfPage: ogImage }];
  }

  // Company pages: contact / team / portfolio.
  const pageType = path === 'contact.html' ? 'ContactPage' : path === 'our-team.html' ? 'AboutPage' : 'CollectionPage';
  return [orgNode(), crumb([{ name: 'Home', url: `${SITE}/` }, { name, url }]), {
    '@type': pageType, '@id': `${url}#webpage`, url, name: title, description,
    about: { '@id': `${SITE}/#organization` }, inLanguage: 'en',
  }];
}

function buildBlock(path, title, description) {
  const url = canonicalFor(path);
  const ogImage = ogImages[path] || LOGO;
  const kw = keywords[path];
  const short = displayName(title);
  const imgAlt = short.toLowerCase().includes('creaiva') ? short : `${short} — CREAIVA`;
  const ld = { '@context': 'https://schema.org', '@graph': graphFor(path, title, description, ogImage) };

  const lines = [
    START,
    `<link rel="canonical" href="${esc(url)}" />`,
    `<meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1" />`,
    kw ? `<meta name="keywords" content="${esc(kw)}" />` : null,
    `<meta name="author" content="CREAIVA" />`,
    `<meta name="publisher" content="CREAIVA" />`,
    `<meta name="geo.region" content="AE-DU" />`,
    `<meta name="geo.placename" content="${esc(GEO)}" />`,
    `<meta name="theme-color" content="#03060d" />`,
    // Open Graph
    `<meta property="og:type" content="website" />`,
    `<meta property="og:site_name" content="CREAIVA" />`,
    `<meta property="og:locale" content="en_US" />`,
    `<meta property="og:title" content="${esc(title)}" />`,
    `<meta property="og:description" content="${esc(description)}" />`,
    `<meta property="og:url" content="${esc(url)}" />`,
    `<meta property="og:image" content="${esc(ogImage)}" />`,
    `<meta property="og:image:alt" content="${esc(imgAlt)}" />`,
    // Twitter
    `<meta name="twitter:card" content="summary_large_image" />`,
    `<meta name="twitter:title" content="${esc(title)}" />`,
    `<meta name="twitter:description" content="${esc(description)}" />`,
    `<meta name="twitter:image" content="${esc(ogImage)}" />`,
    `<script type="application/ld+json">${JSON.stringify(ld)}</script>`,
    END,
  ].filter(Boolean);
  return lines.join('\n');
}

// Read titles/descriptions first (needed for the homepage offer catalogue).
const titles = {};
const descriptions = {};
const sources = {};
for (const path of paths) {
  const html = await readFile(resolve(root, path), 'utf8');
  sources[path] = html;
  titles[path] = (html.match(/<title>([\s\S]*?)<\/title>/) || [, path])[1].trim();
  descriptions[path] = (html.match(/<meta name="description" content="([\s\S]*?)"\s*\/?>/) || [, ''])[1].trim();
}

const check = process.argv.includes('--check');
let changed = 0;
for (const path of paths) {
  let html = sources[path];
  const block = buildBlock(path, titles[path], descriptions[path]);
  const markerRe = new RegExp(`${START.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[\\s\\S]*?${END}`);
  let next;
  if (markerRe.test(html)) {
    next = html.replace(markerRe, block);
  } else {
    // Insert right after the favicon link, which every page carries exactly once.
    next = html.replace(/(<link rel="icon"[^>]*>\s*)/, `$1${block}\n`);
    if (next === html) throw new Error(`Could not find favicon anchor in ${path}`);
  }
  if (next !== html) {
    changed++;
    if (check) { console.error(`SEO metadata out of date in ${path}`); }
    else await writeFile(resolve(root, path), next);
  }
}

// sitemap.xml — every indexable public page.
const today = new Date().toISOString().slice(0, 10);
const priority = p => (p === 'index.html' ? '1.0' : p.startsWith('services/') || p.startsWith('solutions/') ? '0.8' : '0.6');
const sitemap = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
  paths.map(p => `  <url>\n    <loc>${canonicalFor(p)}</loc>\n    <lastmod>${today}</lastmod>\n    <changefreq>monthly</changefreq>\n    <priority>${priority(p)}</priority>\n  </url>`).join('\n') +
  `\n</urlset>\n`;

const robots = `# https://creaiva.online robots policy\nUser-agent: *\nAllow: /\nDisallow: /sales-pricing.html\n\nSitemap: ${SITE}/sitemap.xml\n`;

if (check) {
  const smOld = await readFile(resolve(root, 'sitemap.xml'), 'utf8').catch(() => '');
  const rbOld = await readFile(resolve(root, 'robots.txt'), 'utf8').catch(() => '');
  // lastmod changes daily; compare structure by stripping it.
  const strip = s => s.replace(/<lastmod>.*?<\/lastmod>/g, '');
  if (changed || strip(smOld) !== strip(sitemap) || rbOld !== robots) {
    throw new Error('SEO output is out of date. Run `npm run build:seo` and commit the result.');
  }
  console.log(`SEO metadata current across ${paths.length} pages.`);
} else {
  await writeFile(resolve(root, 'sitemap.xml'), sitemap);
  await writeFile(resolve(root, 'robots.txt'), robots);
  console.log(`Injected SEO metadata into ${changed} of ${paths.length} pages; wrote sitemap.xml and robots.txt.`);
}
